name: CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Upload app file
        uses: actions/upload-artifact@v2.2.4
        with:
          name: demo
          path: ${{ github.workspace }}/target/demo-0.0.1-SNAPSHOT.jar
  deploy_dev:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download app file
        uses: actions/download-artifact@v2.0.10
        with:
          name: demo
      - name: Azure WebApp
        uses: Azure/webapps-deploy@v2
        with:
          app-name: techshot-pipelines
          publish-profile: ${{ secrets.APP_SERVICE_PUBLISH_PROFILE }}
          package: demo-0.0.1-SNAPSHOT.jar
